### ISSUE TITLE
Script Failing @ Set-IamPermissions

### ISSUE THREAD

**Issue by sqlbliss** [microsoft/Nonprofit_Data_Warehouse_Quickstart#3] opened 2020-06-29 17:27 UTC
Script is failing @ Set-IamPermission, it just errors out no other details

**Comment by sqlbliss** [comment] 2020-06-29 18:54
### Script Succeeded - Create-SqlServerMsi
### Script Started
### Script Failed
### Script Started
### Script Failed
KeyVault Name: ymcadwkveusprod
Resource Group: ymcadwrgeusprod

Principals Count: 3


PrincipalName: ymcadwadfeusprod
### Script Executed with Errors - DeployOrchestrator
Set-SecretsAccessPolicy : A parameter cannot be found that matches parameter name 'DisplayName'.
At D:\GitHub\y\Deployment\Scripts\Add-KeyVaultPolicy.ps1:185 char:2
+     Set-SecretsAccessPolicy `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SecretsAccessPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-SecretsAccessPolicy

**Comment by elucht** [comment] 2020-06-29 21:20
Currently under investigation.

**Comment by elucht** [comment] 2020-06-29 21:54
It would appear that one of the variables in the json array is either not set correctly for the given principle or it is not valid according to the naming convention.  If you add the following to line 186 in the Add-KeyVault Policy.ps1 script, you will get the array values that it is attempting to execute when the command fails.

    Write-Host "PrincipalName: $($principal.PrincipalType)";
    Write-Host "PrincipalName: $($principal.PermisionsToSecrets)";
    Write-Host "PrincipalName: $($principal.PermissionsToKeys)";
    Write-Host "PrincipalName: $($keyVaultName)";
    Write-Host "PrincipalName: $($resourceGroup)";

Both KeyVault Name and Resource Group name look good as these are output above in the script.

Additionally, it would appear that there were failures earlier in the scripting.  There are a series of Script Started, Script Failed.  Did it indicate what script failed in your command window?

Have you confirmed the correct permissions for the installing account?  The account that is performing the installation must be included explicitly as an owner in the admins security group.

**Comment by sqlbliss** [comment] 2020-06-29 23:01
Hi
Thanks for the quick response!    I'm kind of stuck - can't figure out what
went wrong.
The 2 scripts that show as failed before the fatal error were
the Set-IamPermissions.ps1 and the Set-KeyVaultSecret.ps1,  no details as
to why those two scripts failed?
That is why the Add-KeyVaultPoliy.ps1 failed  and stopped the process,
there is not a setting for the header parameter from the previous two
failed scripts.

 I attached the full output - I have also run the script with just the
default naming convention other than the 3 required parameters and it
failed at the same place,
 I made sure that my admin onmicrosoft account is in the Admin security
group, which is also the account that was connected to - it did create all
the resources
Any guidance you could provide would be appreciated,

**Comment by sqlbliss** [comment] 2020-06-30 12:54
### Script Executed Successfully
### Script Started - Create-SqlServerMsi

ResourceGroupName        : ymcadwrgeusprod
ServerName               : ymcadwsqleusprod
Location                 : eastus
SqlAdministratorLogin    : quickstartcdmadmin
SqlAdministratorPassword : 
ServerVersion            : 12.0
Tags                     : {[Project, YmcaDW], [Environment, Prod]}
Identity                 : Microsoft.Azure.Management.Sql.Models.ResourceIdentity
FullyQualifiedDomainName : ymcadwsqleusprod.database.windows.net

### Script Succeeded - Create-SqlServerMsi
### Script Started
### Script Failed
### Script Started
### Script Failed
KeyVault Name: ymcadwkveusprod
Resource Group: ymcadwrgeusprod

Principals Count: 3


PrincipalName: ymcadwadfeusprod
PrincipalName: ServicePrincipal
PrincipalName: get list
PrincipalName: list
PrincipalName: ymcadwkveusprod
PrincipalName: ymcadwrgeusprod
### Script Executed with Errors - DeployOrchestrator
Set-SecretsAccessPolicy : A parameter cannot be found that matches parameter name 'DisplayName'.
At D:\GitHub\y\Deployment\Scripts\Add-KeyVaultPolicy.ps1:191 char:2
+     Set-SecretsAccessPolicy `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SecretsAccessPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-SecretsAccessPolicy

**Comment by elucht** [comment] 2020-06-30 18:35
Thank you for your additional information.  What I would suspect is that either KeyVault or the keys or secrets did not get created correctly.  This is typically due to a permissions issue.  We will take a look at adding some additional logging.  

Probably best to have someone take a look with you.  Can you provide your email address or contact information and I can schedule a time to look with you?  Alternatively you can reach out to the Tech for Social Impact team with Microsoft, and either engage with Stephen Green, who is our our solution specialist, or with your account manager, and they can plan a time for us to look at this with you.

**Comment by sqlbliss** [comment] 2020-06-30 19:55
Thanks I have a meeting with Stephen Green at 3:30 today. 

Karen

**Comment by elucht** [comment] 2020-07-02 14:19
This particular issue has been tracked down to an issue with Powershell.  The failure in the scripting was resolved by installing from a newly provisioned VM with default Powershell configurations.  We will continue to review the Powershell environment and will further update documentation as issues is fully understood.

**Closed as completed by elucht** 2020-07-02 14:19 UTC
